CC = cc
CFLAGS = -Wall -Wextra -Werror
NAME = libft.a
ARFLAGS = rcs

SRCS = ft_isprint.c ft_isdigit.c ft_strchr.c ft_isalnum.c ft_isascii.c ft_strncmp.c \
	ft_strlen.c ft_strrchr.c ft_isalpha.c ft_tolower.c ft_toupper.c ft_atoi.c \
	ft_memcpy.c ft_memset.c ft_bzero.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
	ft_memchr.c ft_memcmp.c ft_strnstr.c ft_calloc.c ft_strdup.c ft_putnbr_fd.c \
	ft_putendl_fd.c ft_putchar_fd.c ft_putstr_fd.c ft_strmapi.c ft_strjoin.c \
	ft_striteri.c ft_substr.c ft_itoa.c ft_strtrim.c ft_split.c \
	ft_lstadd_front_bonus.c ft_lstadd_back_bonus.c ft_lstclear_bonus.c \
	ft_lstdelone_bonus.c ft_lstiter_bonus.c ft_lstlast_bonus.c \
	ft_lstnew_bonus.c ft_lstsize_bonus.c ft_realloc.c ft_strcmp.c


OBJS = $(SRCS:.c=.o)

# Default Rule
all: $(NAME)

# Rule to Compile Object Files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Rule to Create the Library
$(NAME): $(OBJS)
	ar $(ARFLAGS) $@ $^


# Clean Rules
clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

# Rebuild Rule
re: fclean all

.PHONY: all clean fclean re
